version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
